### ISSUE TITLE
Can't generate translations

### ISSUE THREAD

**Issue by purohit** [michaeljones/elm-message-format-experiment#1]
Hello,

I was trying to use this for a pet project of mine, and the `generate` command doesn't fail, but I don't get any actual translations. The generated `Translations.elm` file shows:

```
module Translation exposing (..)

import Json.Decode.Pipeline exposing (decode, optional, optionalAt)
import Json.Decode exposing (decodeValue, string)
import Html exposing (Html, text)
import MessageFormat


type Translation
    = TrLanguagesEn
    | TrLanguagesDe


type alias Language =
    { code__ : String
    , languagesEn : String
    , languagesDe : String
    }
```

where I would expect `type Translation` to be a union type of all the translations in the respective .json files, not the languages, as in the README example. I'm running:

```node elm-i18n-from-json.js generate elm-message-format.json Translations.elm``` from a directory like the following:

```
├── de.json
├── elm-i18n-from-json.js
├── elm-message-format.json
├── en.json
└── Translations.elm
```

My `elm-message-format.json` looks like:

```
{
    "languages": {
        "en": "en.json",
        "de": "de.json"
    }
}
```
My `en.json` file for example looks like:

```
{
    "insertExampleText": "Insert an example",
    "loading": "Loading ...",
}
```

I'm fairly sure the file `elm-message-format.json` and corresponding `[lang].json` files are not really being parsed, because if I change the filepaths like `en.json` to `nonexistent.json`, nothing changes in the Translations.elm output. Any thoughts?

Thanks!

**Comment by michaeljones** [comment]
Hi! Thanks for raising this. Sorry for the trouble. It seems that the README & the code drifted apart at some stage. I have adjusted it now. The json file that points to the different languages is no longer expected and instead you provide one of the language files as the first argument. This should work as all the language files should have the same structure.

I believe my intention was that the 'validate' action would use the json file that points to the different languages and use it to check that they all match.

Unfortunately, I have not maintained this project well. I still use it for my work project and it works well but I ended up making some hasty changes and then finally copying the code into my project so that it could be maintained with the rest of the code base instead of expecting my colleagues to have a copy of this around. I would not be very confident in publishing this to npm as it still feels like an experiment!

Anyway, I hope that helps. Thanks for trying it. Let me know if there are any issues.

**Comment by purohit** [comment]
I see, thanks for the clarification. Now when I generate the code, I get the correct union types, but the `translate` function does not contain the strings I was expecting, instead it has lots of JSON decoders. Am I understanding correctly: strings are no longer embedded in the `Translations.elm` file, rather you provide a JSON file at runtime and decode it?

**Comment by michaeljones** [comment]
Yes. The idea is that the elm code shouldn't have all the languages embedded it in and instead it should be in a position to decode all the language info as json coming from the server. If you would like the json embedded then this talk covers one approach to that which seems promising: https://www.youtube.com/watch?v=RcHV6R-Jq00

Sorry it hasn't quite met your expectations! Now that I read the README again, I can see that it very much sounds like the strings should be embedded in the compiled elm file. Sorry for being misleading. I'll attempt to adjust the wording.

**Comment by purohit** [comment]
No problem, thanks for responding and I do understand your approach. The place in the README that specifically confused me because it seemed like strings was embedded in the file was here:

```
translate : Language -> Translation -> String
translate language token =
    case language of
        En_gb ->
            case token of
                TrTextSubText ->
                    MessageFormat.format "en-gb" "Hello, World!"

                TrTextAnotherSubText ->
                    MessageFormat.format "en-gb" "Goodbye, World!"

                TrTopLevelString ->
                    MessageFormat.format "en-gb" "This string is top level"

                TrWithArgsSimple args ->
                    MessageFormat.formatWithArgs "en-gb" "So {wow}" args
```

Anyway, thanks for your efforts, I really like the idea!

**Comment by michaeljones** [comment]
Wow, I didn't even read that far. The code examples are just out of date as I haven't given this project the time it deserves whilst updating it. I'm very sorry for the confusion. I'll try to adjust it today to be up to date!
